name: magtense-env
channels:
  - https://software.repos.intel.com/python/conda
  - https://software.repos.intel.com/python/conda/
  - nvidia/label/cuda-12.6.3
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - anaconda-anon-usage=0.5.0=py312hfc0e8ea_100
  - anaconda-cli-base=0.4.1=py312h06a4308_1
  - anaconda-client=1.13.0=py312h06a4308_0
  - annotated-types=0.6.0=py312h06a4308_0
  - anyio=4.6.2=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.2.0=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_1
  - blas=1.0=openblas
  - bleach=6.2.0=py312h06a4308_0
  - boltons=23.0.0=py312h06a4308_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.8.30=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_0
  - chardet=4.0.0=py312h06a4308_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - cmarkgfm=2022.10.27=py312h5eee18b_0
  - colorama=0.4.6=py312h06a4308_0
  - comm=0.2.1=py312h06a4308_0
  - compiler_shared=2025.0.1=intel_1240
  - conda=24.11.0=py312h06a4308_0
  - conda-build=24.11.2=py312h06a4308_0
  - conda-index=0.5.0=py312h06a4308_0
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312h06a4308_0
  - conda-package-streaming=0.11.0=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cryptography=43.0.3=py312h7825ff9_1
  - cuda-cccl_linux-64=12.6.77=0
  - cuda-crt-dev_linux-64=12.6.85=0
  - cuda-crt-tools=12.6.85=0
  - cuda-cudart=12.6.77=0
  - cuda-cudart-dev=12.6.77=0
  - cuda-cudart-dev_linux-64=12.6.77=0
  - cuda-cudart-static=12.6.77=0
  - cuda-cudart-static_linux-64=12.6.77=0
  - cuda-cudart_linux-64=12.6.77=0
  - cuda-driver-dev_linux-64=12.6.77=0
  - cuda-nvcc=12.6.85=0
  - cuda-nvcc-dev_linux-64=12.6.85=0
  - cuda-nvcc-impl=12.6.85=0
  - cuda-nvcc-tools=12.6.85=0
  - cuda-nvcc_linux-64=12.6.85=0
  - cuda-nvrtc=12.6.85=0
  - cuda-nvvm-dev_linux-64=12.6.85=0
  - cuda-nvvm-impl=12.6.85=0
  - cuda-nvvm-tools=12.6.85=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312h06a4308_0
  - docutils=0.18.1=py312h06a4308_3
  - dpcpp-cpp-rt=2025.0.1=intel_1240
  - dpcpp_impl_linux-64=2025.0.1=intel_1240
  - dpcpp_linux-64=2025.0.1=intel_1240
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozendict=2.4.2=py312h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_1
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - ifx_impl_linux-64=2025.0.1=intel_1240
  - ifx_linux-64=2025.0.1=intel_1240
  - importlib-metadata=8.5.0=py312h06a4308_0
  - intel-cmplr-lib-rt=2025.0.1=intel_1240
  - intel-cmplr-lib-ur=2025.0.1=intel_1240
  - intel-cmplr-lic-rt=2025.0.1=intel_1240
  - intel-fortran-rt=2025.0.1=intel_1240
  - intel-opencl-rt=2025.0.1=intel_1240
  - intel-openmp=2025.0.1=intel_1240
  - intel-sycl-rt=2025.0.1=intel_1240
  - ipykernel=6.29.5=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py312h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=3.1.4=py312h06a4308_1
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py312h06a4308_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.2.5=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - kernel-headers_linux-64=4.18.0=h8bc681e_7
  - keyring=24.3.1=py312h06a4308_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.7.4=hfab0078_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.6.4.1=0
  - libcublas-dev=12.6.4.1=0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libcusparse=12.5.4.2=0
  - libcusparse-dev=12.5.4.2=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - liblief=0.12.3=h6a678d5_0
  - libllvm14=14.0.6=hecde1de_4
  - libmamba=1.5.11=hfe524e5_0
  - libmambapy=1.5.11=py312haf1ee3a_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnvjitlink=12.6.85=0
  - libnvjitlink-dev=12.6.85=0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_1
  - matplotlib-base=3.9.2=py312hbfdbfaf_1
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.2.0=py312h06a4308_0
  - meson=1.6.0=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - mkl=2025.0.1=intel_14
  - mkl-include=2025.0.1=intel_14
  - mkl-static=2025.0.1=intel_14
  - more-itertools=10.3.0=py312h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=py312h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - notebook=7.2.2=py312h06a4308_1
  - notebook-shim=0.2.3=py312h06a4308_0
  - numpy=2.1.3=py312h2809609_0
  - numpy-base=2.1.3=py312he1a6c75_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.0=hb9d3cd8_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.0.0=py312hfdbf927_0
  - pip=24.2=py312h06a4308_0
  - pkginfo=1.10.0=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - prometheus_client=0.21.0=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py312h6a678d5_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py312h06a4308_0
  - pydantic-core=2.20.1=py312hb02cf49_0
  - pydantic-settings=2.6.1=py312h06a4308_0
  - pygments=2.15.1=py312h06a4308_1
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.7=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-dotenv=0.21.0=py312h06a4308_0
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - readchar=4.0.5=py312h06a4308_0
  - readline=8.2=h5eee18b_0
  - readme_renderer=40.0=py312h06a4308_0
  - referencing=0.30.2=py312h06a4308_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_1
  - requests-toolbelt=1.0.0=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986=1.4.0=pyhd3eb1b0_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rich=13.9.4=py312h06a4308_0
  - rpds-py=0.10.6=py312h4aa5aa6_1
  - ruamel.yaml=0.18.6=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py312h5eee18b_0
  - secretstorage=3.3.1=py312h06a4308_1
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=72.1.0=py312h06a4308_0
  - shellingham=1.5.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.28=h8bc681e_7
  - tbb=2022.0.0=intel_402
  - tbb-devel=2022.0.0=intel_402
  - tcm=1.2.0=intel_589
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - truststore=0.8.0=py312h06a4308_0
  - twine=5.1.1=pyhd8ed1ab_0
  - typer=0.9.0=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - umf=0.9.1=intel_6
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py312h2c38b39_1
  - zstd=1.5.6=hc292b87_0
