on:
  release:
    types: [published]

jobs:
  build-and-testing:
    name: Build and test pip-wheels
    uses: ./.github/workflows/linux-python-package-conda.yml
  
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build-and-testing
    environment:
      name: testpypi
      url: https://test.pypi.org/project/magtense/
    permissions:
      id-token: write
    steps:
    - name: Download py312 pip-wheel
      uses: actions/download-artifact@v4
      with:
        name: pip-wheel-py312-cu12

    - name: Download py313 pip-wheel
      uses: actions/download-artifact@v4
      with:
        name: pip-wheel-py313-cu12

    - name: Move wheels to dist/
      run: |
        mkdir dist/
        mv ${{ github.workspace }}/*.whl dist/
        ls -al dist/

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
